#!/bin/bash

IMGPATH="../Figures"
IMGNUMBER=$(ls $IMGPATH/map*png | wc -l)
IMGLISTID=$(seq -w 1 $IMGNUMBER)
IMGLISTNAMES=$(for i in $IMGLISTID; do echo map$i.png; done;)
SLIDES=$(for i in $IMGLISTNAMES; do echo '<div><img src="'$IMGPATH/$i'"></div>'; done;)
NAVOUT=$(for i in $IMGLISTID; do echo '<i></i> '; done;)

#echo $SLIDES
#echo $NAVOUT

cat  << EOF
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>bamboo demo</title>
    <link rel="stylesheet" type="text/css" href="css/bamboo.css">
    <script type="text/javascript" src="js/bamboo.js"></script>
    <style type="text/css">
    .demo {
        margin: auto;
        width: 480px;
        height: 480px;
        overflow: hidden;
        border: 10px solid #fefefe;
        box-shadow: 1px 1px 8px 2px rgba(0, 0, 0, .1);
    }

    .out-nav {
        text-align: center;
    }

    .out-nav>i {
        display: inline-block;
        margin: 4px;
        width: 10px;
        height: 10px;
        border-radius: 50%;
        border: 1px solid #aaa;
    }

    .out-nav>i.focus {
        background: #ff0;
    }

    .out-btn {
        text-align: center;
    }

    .out-btn>button {
        margin: 2px;
        width: 100px;
        height: 35px;
        outline: 0;
        border: 0;
        background: #479FA4;
        color: #fefefe;
        font-size: 14px;
        border-radius: 4px;
        border-top: 2px solid #76C3C1;
        border-bottom: 2px solid #404E4F;

    }

    .out-arrow>button:hover {
        background: #378F94;
    }
    </style>
</head>

<body>
    <div class="demo">
        <div class="slides">
            $SLIDES
        </div>
    </div>
    <div>
        <div class="out-nav">
            $NAVOUT
        </div>
        <div class="out-btn">
            <button class="out-prev">prev</button>
            <button class="out-next">next</button>
        </div>
    </div>
    <script type="text/javascript">
    var element = document.querySelector('.demo');
    var slideshow = bamboo(element, 'fade', {
        autoPlay: false,
        dots: document.querySelector('.out-nav'),
        prev: document.querySelector('.out-prev'),
        next: document.querySelector('.out-next'),
    });
    </script>
</body>

</html>
EOF
